[package]
name = "bangdream-optimize-bangdream-account"
version = "0.3.5"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
aes.workspace = true
bangdream-optimize-core.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
