[package]
name = "bangdream-optimize-sync-bestdori"
version = "0.3.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bangdream-optimize-core.workspace = true
bangdream-optimize-data.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
