// Ported from the approved custom-card-study v5 design.
export const customCardsMarkup = ` <section id="cc-custom-panel"  class="content">
  <div class="intro"><div><h2><span data-icon="edit"></span>自定义卡牌</h2><p>独立保存与管理，用相同的卡牌规则比较不同方案。</p></div><button type="button" class="primary" id="cc-create"><span data-icon="plus"></span>创建卡牌</button></div>
  <div class="list-tools"><label class="search"><span data-icon="search"></span><input id="cc-search" type="search" placeholder="搜索名称、角色或编号" aria-label="搜索自定义卡牌"></label><div class="attribute-filter" id="cc-attribute-filter" role="group" aria-label="筛选自定义卡牌属性"></div><label class="sort-label">排序<select id="cc-sort" aria-label="自定义卡牌排序"><option value="updated">最近修改</option><option value="power">综合力</option><option value="rarity">稀有度</option></select></label></div>
  <div class="list-caption"><span id="cc-list-count"></span><span>三维含所设突破 · 不含角色、道具与活动加成</span></div><div id="cc-custom-list"></div>
  <div id="cc-empty" class="empty" hidden><span data-icon="cards"></span><h3>还没有自定义卡牌</h3><p>从三维与技能开始，建立一张用于试算的卡牌。</p><button type="button" class="primary" id="cc-empty-create">创建第一张卡牌</button></div>
  <footer class="study-footer"><span>自定义卡牌独立保存在当前档案中，启用后参与计算。</span></footer>
 </section>
<dialog id="cc-editor" aria-labelledby="cc-editor-title"><form id="cc-card-form">
 <header class="dialog-header"><div><p id="cc-editor-eyebrow">CUSTOM CARD</p><h2 id="cc-editor-title">创建自定义卡牌</h2></div><button type="button" class="icon-button" data-close aria-label="关闭卡牌编辑"><span data-icon="close"></span></button></header>
 <div class="editor-scroll"><div class="editor-layout">
  <aside class="card-preview"><div class="preview-art"><img id="cc-preview-art" alt="自定义卡牌原画"><span class="custom-mark">CUSTOM</span></div><p class="preview-id" id="cc-preview-id"></p><h3 id="cc-preview-name"></h3><p id="cc-preview-character"></p><div class="preview-tags" id="cc-preview-tags"></div><p id="cc-preview-enabled" class="preview-enabled" hidden>未启用 · 不参与计算</p><div class="preview-total"><span>卡牌综合力</span><strong id="cc-preview-total"></strong><small id="cc-preview-break"></small></div><div class="preview-skill"><b id="cc-preview-skill"></b><p id="cc-preview-description"></p></div><p class="preview-hint">随右侧参数实时更新</p></aside>
  <div class="editor-fields">
   <section class="field-section"><div class="section-title identity-title"><h3><span data-icon="identity"></span>基本信息</h3><div class="band-display"><span>所属乐队</span><div id="cc-band-display"></div></div></div><div class="field-grid"><label>卡牌名称<input name="name" maxlength="48" placeholder="留空将按角色自动命名"></label><label>角色<select name="character" required aria-label="自定义卡牌角色"></select></label></div><fieldset class="inline-options"><legend>属性</legend><div id="cc-attribute-options"></div></fieldset><fieldset class="inline-options"><legend>稀有度</legend><div id="cc-rarity-options"></div></fieldset><div class="enabled-field"><div><span>参与计算</span><p>停用后保留卡牌配置，可随时重新启用。</p></div><label class="form-enable"><input name="enabled" type="checkbox" role="switch" aria-label="启用此自定义卡牌"><span class="switch-track" aria-hidden="true"></span><span id="cc-enabled-label">已启用</span></label></div></section>
   <section class="field-section"><div class="section-title"><h3><span data-icon="power"></span>三维与突破</h3><span id="cc-stat-basis">满级 · 特训后 · 剧情全开</span></div><p class="field-help" id="cc-stat-help">填写 0 突破的三维，突破加值由系统另行计算。</p><div class="stats-inputs" id="cc-stats-inputs"></div><div class="break-line"><label>突破等级 <input type="number" name="mastery" min="0" max="4" step="1" required aria-label="自定义突破等级"><span>/ 4</span></label><span id="cc-break-addition"></span></div></section>
   <section class="field-section skill-section"><h3><span data-icon="skill"></span>技能</h3><label class="skill-template">技能模板<select name="skillType" aria-label="技能模板"><option value="score">普通分数提升</option><option value="perfect">PERFECT 条件加分 · P</option><option value="great">GREAT 以下降档 · G</option><option value="unified">同属性／同乐队条件</option><option value="rateup">PERFECT 递增加分</option></select></label><div class="skill-inputs"><label>持续时间<div class="duration-control"><input name="duration" type="number" inputmode="decimal" step="any" required aria-label="技能持续时间" aria-describedby="cc-duration-help cc-duration-error"><span>s</span><span class="duration-steps"><button type="button" data-duration-step="1" aria-label="下一个可用时长" title="下一个可用时长"><svg viewBox="0 0 16 16" aria-hidden="true"><path d="m4 10 4-4 4 4"/></svg></button><button type="button" data-duration-step="-1" aria-label="上一个可用时长" title="上一个可用时长"><svg viewBox="0 0 16 16" aria-hidden="true"><path d="m4 6 4 4 4-4"/></svg></button></span></div></label><label><span id="cc-score-label">加成</span><div><input type="number" name="score" min="0" max="1000" step="0.5" required aria-label="技能加成"><span>%</span></div></label></div>
    <p id="cc-duration-help" class="field-help duration-help"></p><p id="cc-duration-error" class="field-error" role="alert" hidden></p>
    <div id="cc-unified-fields" class="conditional-fields" hidden><div class="field-grid"><label id="cc-condition-attribute-label">全队属性<select name="conditionAttribute"><option value="none">不限制</option><option>Powerful</option><option>Cool</option><option>Happy</option><option>Pure</option></select></label><label id="cc-condition-band-label">全队乐队<select name="conditionBand"></select></label><label>触发后加成<div class="unit-input"><input name="unifiedScore" type="number" min="0" max="1000" step="0.5" required><span>%</span></div></label></div><p id="cc-condition-help">不限制表示不检查该项；设置两项时需要同时满足。</p></div>
    <div id="cc-great-fields" class="conditional-fields" hidden><label>降档后加成<div class="unit-input"><input name="lowerScore" type="number" min="0" max="1000" step="0.5" required><span>%</span></div></label><p>沿用现有 G 型技能，理想演奏按未降档状态计算。</p></div><p id="cc-rateup-note" class="field-help" hidden>起始加成固定为 100%，每个 PERFECT +0.5%，最高 150%。</p>
    <p id="cc-skill-description-inline" class="skill-description-inline"></p>
   </section>
   <details class="extra-section"><summary><span data-icon="image"></span>图片与备注 <small>可选</small><span data-icon="chevron"></span></summary><div class="extra-body"><p class="field-help">选择参考原画或上传图片；仅改变展示。</p><div id="cc-art-gallery" class="art-gallery"></div><label class="upload">上传图片<input id="cc-image-file" type="file" accept="image/png,image/jpeg,image/webp"></label><p id="cc-image-error" class="error" role="status"></p><label>备注<textarea name="notes" rows="2" maxlength="240" placeholder="记录这个方案的用途"></textarea></label></div></details>
   <details class="extra-section"><summary><span data-icon="growth"></span>高级养成设置 <small>可选</small><span data-icon="chevron"></span></summary><div class="extra-body"><label class="enable-growth"><input name="advancedEnabled" type="checkbox">按等级、特训和剧情分项计算</label><p class="field-help">启用后，三维改为当前等级的基础值。特训与剧情加值单独填写；初始为 0，避免重复计入。</p><div id="cc-advanced-fields" hidden><label class="current-level">当前卡牌等级<select name="cardLevel" aria-label="当前自定义卡牌等级"></select></label><div class="level-heading"><span>等级</span><span>演出</span><span>技巧</span><span>形象</span><span></span></div><div id="cc-level-rows"></div><button type="button" class="text-button" id="cc-add-level">＋ 添加等级数据</button><div id="cc-growth-bonuses"></div><p class="field-help">只允许选择已填写的等级。关闭分项模式时，将当前状态折算为固定三维。</p></div></div></details>
  </div>
 </div></div><footer class="dialog-footer"><p id="cc-form-status" role="status">保存到当前档案的自定义列表</p><div><button type="button" class="text-button" data-close>取消</button><button type="submit" class="primary">保存卡牌</button></div></footer>
</form></dialog>
<dialog id="cc-confirm-dialog" aria-labelledby="cc-confirm-title"><h2 id="cc-confirm-title"></h2><p id="cc-confirm-copy"></p><div><button id="cc-confirm-cancel" class="text-button">取消</button><button id="cc-confirm-accept" class="primary">确认</button></div></dialog>
<div class="toast" id="cc-toast" role="status" hidden></div>`;
