[package]
name = "bangdream-optimize-storage-mongodb"
version = "0.3.3"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
bangdream-optimize-core.workspace = true
bangdream-optimize-data.workspace = true
mongodb.workspace = true
thiserror.workspace = true

