[package]
name = "bangdream-optimize-web-wasm"
version = "0.2.2"
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bangdream-optimize-core.workspace = true
bangdream-optimize-data.workspace = true
serde.workspace = true
serde_json.workspace = true
wasm-bindgen.workspace = true
