import {assetImage,attributeIconUrls,characterIconUrls,cardIconUrls,starIconUrls} from '../assets/index.js';
import {gameText} from './preferences.js';
import {designIcon} from './fidelity.js';
import {attributeNames} from './cards/rules.js';
import {createFilterControls} from './cards/filters.js';
import {createCardCatalog,toggleSelectionScope} from './cards/catalog.js';
import {catalogModels} from './cards/model.js';
import {allowedLiveVariants,ptEvaluateLiveVariant,ptMaximizeLiveVariant} from '../models/player-settings.js';
import {bonusApplication} from './activity.js';

const el=(tag,cls,text)=>{const n=document.createElement(tag);n.className=cls||'';if(text!==undefined)n.textContent=text;return n;};
const button=(text,fn,cls='pb-link')=>{const b=el('button',cls,text);b.type='button';b.onclick=fn;return b;};
const eventNames={mission_live:'任务 Live',live_try:'Live Try',challenge:'挑战 Live',versus:'竞演 Live',festival:'团队 Live',medley:'巡回演出'};
const liveNames={solo:'单人演奏',cooperative:'协力演奏',challenge_cp:'挑战 Live · CP',versus:'竞演 Live',festival:'团队 Live',medley:'巡回演出'};

export function openBonusEditor({getPlayer,getCore,getProfileId,eventSnapshot,writePlayer,renderForms}){
 const root=document.querySelector('#aurora-soft-study'),player=getPlayer(),profile=getProfileId(),draft=structuredClone(eventSnapshot(player.currentEvent,player));
 const mode=player.calculationMode,lives={...(mode==='ptMaximize'?player.ptMaximize:player.ptEvaluate)?.liveVariantByEventType};let point=false;
 const characters=Object.entries(getCore().characters).filter(([,c])=>c.bandId>0&&c.bandId<100).map(([id,c])=>({id:Number(id),band:Number(c.bandId),name:gameText(c.characterName,`角色 ${id}`)}));
 const dialog=el('dialog','pb-dialog shared-card-library');dialog.setAttribute('aria-label','编辑活动加成');const form=el('form');form.method='dialog';dialog.append(form);
 form.innerHTML='<header class="pb-dialog-header"><div><p class="pb-eyebrow"></p><h2>编辑活动加成</h2></div><button type="button" class="pb-icon-button" aria-label="关闭加成编辑">×</button></header><div class="pb-scroll"><p class="pb-copy-note">选择活动类型和演奏方式，自动识别加成模型。不同模型的匹配数值分别保留。</p></div><footer class="pb-dialog-footer"><p>应用后生效</p><button type="button" data-cancel class="pb-link">取消</button><button type="submit" class="pb-primary">应用加成</button></footer>';
 form.querySelector('.pb-eyebrow').textContent=Number(player.currentEvent)?`来自活动 #${player.currentEvent} · 应用后创建自定义活动`:'当前档案 · 自定义活动';form.querySelector('.pb-icon-button').onclick=form.querySelector('[data-cancel]').onclick=()=>dialog.close();
 const body=form.querySelector('.pb-scroll');
 const numeric=(value,change,label)=>{const input=el('input');input.type='number';input.min=0;input.step='any';input.required=true;input.value=Number(Number(value||0).toFixed(4));if(label)input.setAttribute('aria-label',label);input.oninput=()=>{if(input.validity.valid)change(Number(input.value));};return input;};
 const section=(title,iconName,extra)=>{const s=el('section','pb-editor-section'),head=el('div','pb-section-heading'),h=el('h3','',title);h.insertAdjacentHTML('afterbegin',designIcon(iconName));head.append(h);if(extra)head.append(extra);s.append(head);body.append(s);return s;};
 const scene=el('div','pb-scene');scene.innerHTML='<div class="pb-scene-fields"><label>活动类型<select aria-label="加成活动类型"></select></label><label>演奏方式<select aria-label="加成演奏方式"></select></label></div><p class="pb-help pb-scene-note">自动识别：<strong role="status"></strong><span>只显示对应的加成字段</span></p>';body.append(scene);const[type,live]=scene.querySelectorAll('select');for(const[id,label]of Object.entries(eventNames))type.add(new Option(label,id));type.value=draft.eventType;
 const attributeSection=section('属性加成','bonus',el('small','','勾选参与加成的属性')),attrs=el('div','pb-attribute-editor');attributeSection.append(attrs);
 for(const[attr,name]of Object.entries(attributeNames)){let entry=draft.attributes.find(a=>a.attribute===attr);const row=el('div','pb-attribute-item'),toggle=el('label','pb-attribute-toggle'),check=el('input');check.type='checkbox';check.checked=!!entry;toggle.append(check,assetImage(attributeIconUrls(attr),'',name),el('span','',name));const rate=el('span','pb-attribute-rate'),input=numeric(entry?.percent??20,v=>{if(entry)entry.percent=v;},`${name}加成百分比`);input.disabled=!entry;rate.append(input,document.createTextNode('%'));row.append(toggle,rate);attrs.append(row);check.onchange=()=>{draft.attributes=draft.attributes.filter(a=>a.attribute!==attr);entry=check.checked?{attribute:attr,percent:Number(input.value)||0}:undefined;if(entry)draft.attributes.push(entry);input.disabled=!entry;};}
 const actions=el('div'),charSection=section('角色加成','player',actions),bands=el('div','pb-bands'),rates=el('div','pb-character-rates');charSection.append(bands);const filters={character:new Set(draft.characters.map(c=>String(c.characterId)))};
 const batch=(parent,kind,repaint)=>{const bar=el('div','pb-batch'),label=el('label','','统一百分比 '),span=el('span'),input=numeric(20,()=>{},kind==='characters'?'角色统一加成百分比':'卡牌统一加成百分比');span.append(input,document.createTextNode('%'));label.append(span);bar.append(label,button('应用到已选'+(kind==='characters'?'角色':'卡牌'),()=>{if(!input.reportValidity())return;for(const entry of draft[kind])entry.percent=Number(input.value);repaint();}),el('small','','可在下方单独调整'));parent.append(bar);};
 const renderRates=()=>{rates.replaceChildren();for(const entry of draft.characters){const name=characters.find(c=>c.id===entry.characterId)?.name||`角色 ${entry.characterId}`,label=el('label','pb-character-rate'),span=el('span');label.title=name;label.append(assetImage(characterIconUrls(entry.characterId),'',name));span.append(numeric(entry.percent,v=>entry.percent=v,`${name}加成百分比`),document.createTextNode('%'));label.append(span);rates.append(label);}if(!draft.characters.length)rates.append(el('p','pb-help','尚未选择角色。'));};
 const controls=createFilterControls(charSection,{characters,getFilters:()=>filters,onChange:()=>{const prev=new Map(draft.characters.map(c=>[String(c.characterId),c]));draft.characters=[...filters.character].map(id=>prev.get(id)||{characterId:Number(id),percent:20});controls.update();renderRates();},hosts:{character:bands},actionHosts:{character:actions}});batch(charSection,'characters',renderRates);charSection.append(rates);renderRates();
 const membersSection=section('指定卡牌','cards',button('选择卡牌',pickCards)),members=el('div','pb-member-rates');batch(membersSection,'members',renderMembers);membersSection.append(members);
 function renderMembers(){members.replaceChildren();for(const entry of draft.members){const card=getCore().cards[entry.situationId],row=el('div','pb-member-rate'),info=el('div'),name=gameText(card?.prefix,`卡牌 ${entry.situationId}`);row.append(assetImage(cardIconUrls({cardId:entry.situationId,card,illustTrainingStatus:true}),'pb-card-art',name));info.append(el('span','pb-member-name',`${name} · #${entry.situationId}`));const field=el('label');field.append(numeric(entry.percent,v=>entry.percent=v,`${entry.situationId} 加成百分比`),document.createTextNode('%'));info.append(field);row.append(info,button('×',()=>{draft.members=draft.members.filter(c=>c!==entry);renderMembers();},'pb-icon-button'));row.querySelector('button').setAttribute('aria-label','移除加成卡牌 '+entry.situationId);members.append(row);}if(!draft.members.length)members.append(el('p','pb-help','未设置。可以从卡牌库选择加成对象。'));}renderMembers();
 const match=section('属性与角色同时匹配','target'),help=el('p','pb-help'),fields=el('div','pb-match-fields');match.append(help,fields);
 draft.eventAttributeAndCharacterBonus??={};draft.eventCharacterParameterBonus??={};
 const limit=el('details','pb-editor-section pb-limit-editor');limit.innerHTML='<summary>突破加成 <span>展开调整各稀有度的 0–4 阶</span></summary>';const matrix=el('div','mastery-matrix'),matrixHead=el('div','mastery-row');matrixHead.append(el('span'));for(let rank=0;rank<=4;rank++)matrixHead.append(el('span','',`突破 ${rank}`));matrix.append(matrixHead);for(let rarity=5;rarity>=1;rarity--){const row=el('div','mastery-row');row.append(assetImage(starIconUrls(rarity),'',`${rarity} 星`));for(let rank=0;rank<=4;rank++)row.append(numeric(draft.limitBreaks?.find(r=>r.rarity===rarity&&r.rank===rank)?.percent,v=>{draft.limitBreaks=(draft.limitBreaks||[]).filter(r=>r.rarity!==rarity||r.rank!==rank);draft.limitBreaks.push({rarity,rank,percent:v});},`${rarity} 星突破 ${rank} 加成`));matrix.append(row);}limit.append(matrix);body.append(limit);
 function renderScene(){
  const variants=allowedLiveVariants(draft.eventType,mode);const savedValue=mode==='ptMaximize'?ptMaximizeLiveVariant({liveVariantByEventType:lives},draft.eventType):ptEvaluateLiveVariant({liveVariantByEventType:lives},draft.eventType);const value=variants.includes(savedValue)?savedValue:variants[0];live.disabled=variants.length===1;live.replaceChildren(...variants.map(v=>new Option(liveNames[v],v)));live.value=value;scene.querySelector('.pb-scene-note>span').textContent=mode==='scoreRange'?'控分的演奏场景由活动类型确定':mode==='maximize'?'最高得分使用对应活动的综合力模型':'只显示对应的加成字段';point=bonusApplication(draft.eventType,mode,value)==='point';scene.querySelector('strong').textContent=point?'活动 PT 加成':'综合力加成';help.textContent=point?'仅在卡牌同时满足已选属性和角色时叠加活动 PT 加成。':'同时满足属性和角色时增加综合力，也可以分别设置单项能力加成。';fields.dataset.application=point?'point':'stat';fields.replaceChildren();const defs=[[point?'活动 PT':'综合力',draft.eventAttributeAndCharacterBonus,point?'pointPercent':'parameterPercent']];if(!point)for(const[k,n]of[['performance','演出'],['technique','技巧'],['visual','形象']])defs.push([n,draft.eventCharacterParameterBonus,k]);for(const[name,target,key]of defs){const label=el('label','pb-number',name),span=el('span');span.append(numeric(target[key],v=>target[key]=v,name+'加成百分比'),document.createTextNode('%'));label.append(span);fields.append(label);}
 }
 scene.onchange=e=>{if(!form.checkValidity()){form.reportValidity();type.value=draft.eventType;live.value=lives[draft.eventType]||allowedLiveVariants(draft.eventType,mode)[0];return;}if(e.target===type)draft.eventType=type.value;else if(e.target===live)lives[draft.eventType]=live.value;renderScene();};renderScene();
 function pickCards(){
  const picker=el('dialog','pb-dialog accepted-bonus-picker');picker.innerHTML='<header class="pb-dialog-header"><h2>指定加成卡牌</h2><button type="button" class="pb-icon-button" aria-label="关闭加成卡牌选择">×</button></header><div class="pb-scroll accepted-card-picker"></div><footer class="pb-dialog-footer"><p></p><button type="button" data-all>全选筛选结果</button><button type="button" data-cancel>取消</button><button type="button" class="pb-primary">使用所选卡牌</button></footer>';let selected=new Set(draft.members.map(c=>c.situationId));picker.setAttribute('aria-label','指定加成卡牌');root.append(picker);let catalog;const update=()=>{catalog.paintSelection();picker.querySelector('footer p').textContent=`已选 ${selected.size} 张`;};catalog=createCardCatalog({root:picker.querySelector('.pb-scroll'),selectionMode:'bonus',getCards:()=>catalogModels(getCore(),getPlayer(),profile),getCharacters:()=>characters,getProfileId:()=>profile,getServer:()=>getPlayer().server,onPick:c=>{selected.has(c.id)?selected.delete(c.id):selected.add(c.id);update();},selectedIds:()=>[...selected]});catalog.refresh();update();picker.querySelector('[data-all]').onclick=()=>{selected=toggleSelectionScope(selected,catalog.filteredIds());update();};picker.querySelector('.pb-icon-button').onclick=picker.querySelector('[data-cancel]').onclick=()=>picker.close();picker.querySelector('.pb-primary').onclick=()=>{const prev=new Map(draft.members.map(c=>[c.situationId,c]));draft.members=[...selected].map(id=>prev.get(id)||{situationId:id,percent:20});renderMembers();picker.close();};picker.onclose=()=>{catalog.destroy();picker.remove();};picker.showModal();
 }
 form.onsubmit=e=>{e.preventDefault();if(getProfileId()!==profile||!form.reportValidity())return;const latest=getPlayer();latest.eventSongs[0]=structuredClone(latest.eventSongs[latest.currentEvent]||[]);latest.currentEvent=0;latest.eventOverrides[0]=draft;for(const key of ['ptEvaluate','ptMaximize'])latest[key].liveVariantByEventType={...latest[key].liveVariantByEventType,...lives};writePlayer(latest);renderForms(latest);dialog.close();};dialog.onclose=()=>dialog.remove();root.append(dialog);dialog.showModal();
}
