// Copied final archive flow markup, with demonstration controls removed.
const paths = {
 music:'<path d="M9 18V5l12-3v13M9 9l12-3"/><ellipse cx="6" cy="18" rx="3" ry="3"/><ellipse cx="18" cy="15" rx="3" ry="3"/>',
 sliders:'<path d="M4 7h7m5 0h4M4 17h3m5 0h8"/><circle cx="13.5" cy="7" r="2.5"/><circle cx="9.5" cy="17" r="2.5"/>',
 cards:'<rect x="7" y="5" width="13" height="16" rx="2"/><path d="M4 17H3V3h12v1"/>',
 users:'<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3M16 5a3 3 0 0 1 0 6m1 3a5 5 0 0 1 4 5v2"/>',
 chart:'<path d="M4 3v18h17M8 16v-5m5 5V7m5 9V4"/>',
 folder:'<path d="M3 7V4h6l2 3h10v13H3z"/>',
 database:'<ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v14c0 4 16 4 16 0V5M4 12c0 4 16 4 16 0"/>',
 message:'<path d="M3 3h18v14H8l-5 4zM7 7h10M7 11h7"/>',
 arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',
 chevron:'<path d="m7 10 5 5 5-5"/>',
 check:'<path d="m5 12 4 4L19 6"/>',
 more:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>',
 plus:'<path d="M12 5v14M5 12h14"/>',
 search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/>',
 transfer:'<path d="M3 7h17l-4-4m4 14H3l4 4M20 7l-4 4M3 17l4-4"/>',
 close:'<path d="m6 6 12 12M18 6 6 18"/>',
 download:'<path d="M12 3v12m-5-5 5 5 5-5M4 15v6h16v-6"/>',
 upload:'<path d="M12 16V4m-5 5 5-5 5 5M4 15v6h16v-6"/>',
 copy:'<rect x="8" y="8" width="13" height="13" rx="2"/><path d="M16 4V3H3v13h1"/>',
 trash:'<path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7m4-7v7"/>',
 alert:'<path d="m12 3 10 18H2zM12 9v5m0 3v1"/>',
 info:'<circle cx="12" cy="12" r="9"/><path d="M12 10v7m0-11v1"/>',
 refresh:'<path d="M20 7V2m0 5h-5M4 17v5m0-5h5M19 7A8 8 0 0 0 5 6M5 17a8 8 0 0 0 14 1"/>',
 monitor:'<rect x="3" y="3" width="18" height="13" rx="2"/><path d="M12 16v5m-5 0h10"/>',
 file:'<path d="M5 2h9l5 5v15H5zM14 2v6h5M9 12h6m-6 4h6"/>',
 link:'<path d="m9 15 6-6M8 16l-2 2a4 4 0 0 1-6-6l5-5a4 4 0 0 1 6 0m2 1 2-2a4 4 0 0 1 6 6l-5 5a4 4 0 0 1-6 0"/>',
 clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/>'
};
export const archiveIcon = name => `<span data-icon="${name}" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round">${paths[name] || paths.info}</svg></span>`;
export function createProfileMarkup({d,p,r,name="",copy=null,isNew=false,compact=true,payload="",escapeHtml,serverChoices,flagInline,flag,icon,importScope,cardStrip=()=>"",servers,number=String}) {
const stepList = step => `<ol class="step-list" aria-label="导入进度"><li class="${step===1?'active':''}"><i>1</i>读取资料</li><li class="${step===2?'active':''}"><i>2</i>核对变化</li><li class="${step===3?'active':''}"><i>3</i>完成</li></ol>`;
return `<form id="create-form" novalidate><div class="flow-body form-stack"><p class="intro">${copy?'复制卡牌、道具、角色加成及计算配置，方便单独调整。':'先给档案起个名字，之后可以导入已有资料。'}</p><label class="field"><span>档案名称</span><input id="create-name" value="${escapeHtml(name)}" maxlength="40" required aria-describedby="create-error"><small id="create-error" class="field-error"></small></label><fieldset class="server-field"><legend>对应服务器</legend>${serverChoices('create-server',copy?.server||'cn')}</fieldset><label class="compact-check"><input id="activate-created" type="checkbox" checked>创建后切换到这份档案</label></div><div class="dialog-bottom"><button type="button" class="text-button" data-close-flow>取消</button><button type="submit" class="primary">${copy?'创建副本':'创建档案'}</button></div></form>`;
}
export function importSourceMarkup({d,p,r,name="",copy=null,isNew=false,compact=true,payload="",escapeHtml,serverChoices,flagInline,flag,icon,importScope,cardStrip=()=>"",servers,number=String}) {
const stepList = step => `<ol class="step-list" aria-label="导入进度"><li class="${step===1?'active':''}"><i>1</i>读取资料</li><li class="${step===2?'active':''}"><i>2</i>核对变化</li><li class="${step===3?'active':''}"><i>3</i>完成</li></ol>`;
const credentials = d.server==='cn' && d.method==='credentials';
const accountFields = `<div class="cn-account-fields form-stack"><label class="field"><span>Bilibili 账号</span><input id="import-account" name="username" autocomplete="username" maxlength="320" value="${escapeHtml(d.account||'')}" placeholder="手机号、邮箱或用户名" aria-describedby="import-error"></label><label class="field"><span>密码</span><input id="import-password" name="password" type="password" autocomplete="current-password" maxlength="1024" placeholder="输入 Bilibili 账号密码" aria-describedby="import-error"></label><fieldset class="server-field cn-channel"><legend>游戏渠道</legend><div class="cn-import-options">${[['android','bili安卓'],['ios','iOS']].map(([value,label])=>`<label><input name="import-channel" type="radio" value="${value}" ${d.channel===value?'checked':''}><span>${label}</span></label>`).join('')}</div><p class="dialog-note">选择游戏账号所在渠道，与当前使用的电脑或手机无关。</p></fieldset></div><div class="source-hint"><strong>读取此账号的完整养成资料</strong><p>卡牌、区域道具和角色加成只新增和修改，未返回的记录保留；下一步核对后应用。密码仅用于本次读取，不保存在档案中。</p><p>登录可能使游戏中的同一账号被顶下线，请先结束演出。发送请求前会再次确认。</p></div>`;
return `<form id="import-form" novalidate><div class="flow-body">${stepList(1)}<div class="source-tabs"><button type="button" data-source="account" aria-pressed="${d.source==='account'}">${icon('users')}游戏账号</button><button type="button" data-source="paste" aria-pressed="${d.source==='paste'}">${icon('file')}粘贴配置</button></div><div id="source-body">${d.source==='account'?`<fieldset class="server-field" style="margin-top:0"><legend>游戏服务器</legend>${serverChoices('import-server',d.server)}</fieldset>${d.server==='cn'?`<fieldset class="server-field cn-import-method"><legend>读取方式</legend><div class="cn-import-options"><label><input name="import-method" type="radio" value="credentials" ${credentials?'checked':''}><span>账号密码</span></label><label><input name="import-method" type="radio" value="public" ${!credentials?'checked':''}><span>主乐队公开资料</span></label></div></fieldset>`:''}${credentials?accountFields:`<label class="field stack-gap"><span>玩家 ID</span><input id="import-id" inputmode="numeric" placeholder="输入游戏内的玩家 ID" value="${escapeHtml(d.playerId)}" aria-describedby="import-error"></label><div class="source-hint"><strong>仅导入主乐队的公开资料</strong><p>通过 Bestdori 读取主乐队卡牌、对应角色加成与已装备道具。公开资料不包含完整持有卡牌列表。</p></div>`}`:`<div class="form-stack"><label class="field"><span>配置格式</span><select id="import-format"><option value="base64" ${d.format==='base64'?'selected':''}>本工具 · Base64 配置</option><option value="bestdori" ${d.format==='bestdori'?'selected':''}>Bestdori Profile</option></select></label><label class="field"><span>配置内容</span><textarea id="import-text" rows="5" spellcheck="false" placeholder="粘贴导出的配置内容" aria-describedby="import-error">${escapeHtml(d.text)}</textarea></label></div><p class="dialog-note">${d.format==='base64'?'包含游戏卡牌、自定义卡牌、道具和角色加成，服务器使用目标档案的设置。自定义卡牌按唯一标识合并，同编号的不同卡牌会自动分配新编号。':'包含服务器、卡牌、区域道具及潜能；角色任务加成会按现有规则重建。'}</p>`}</div><p id="import-error" class="field-error" role="alert" tabindex="-1"></p><p id="import-progress" class="dialog-note" role="status"></p><p class="dialog-note">导入目标：${flagInline(p.server)} ${escapeHtml(p.name)}。下一步可以改为新建档案。</p></div><div class="dialog-bottom"><button type="button" class="text-button" data-close-flow>取消</button><button type="submit" class="primary">读取并预览 ${icon('arrow')}</button></div></form>`;
}
export function importReviewMarkup({d,p,r,identity=null,name="",copy=null,isNew=false,compact=true,payload="",escapeHtml,serverChoices,flagInline,flag,icon,importScope,cardStrip=()=>"",servers,number=String}) {
const stepList = step => `<ol class="step-list" aria-label="导入进度"><li class="${step===1?'active':''}"><i>1</i>读取资料</li><li class="${step===2?'active':''}"><i>2</i>核对变化</li><li class="${step===3?'active':''}"><i>3</i>完成</li></ol>`;
return `<div class="flow-body">${stepList(2)}<div class="import-summary">${flag(d.server)}<span>${escapeHtml(importScope())}</span></div>${identity?`<dl class="import-identity" aria-label="导入来源账号"><div class="import-identity-name"><dt>用户名</dt><dd>${escapeHtml(identity.name||"未提供")}</dd></div><div><dt>UID</dt><dd>${escapeHtml(identity.gameUid??"未提供")}</dd></div>${Number.isFinite(identity.rank)?`<div><dt>等级</dt><dd>Lv. ${escapeHtml(identity.rank)}</dd></div>`:""}</dl>`:""}<fieldset class="destination"><legend>导入到</legend><div class="destination-options"><label><input name="destination" type="radio" value="current" ${!isNew?'checked':''}>${escapeHtml(p.name)}</label><label><input name="destination" type="radio" value="new" ${isNew?'checked':''}>新建档案</label></div>${isNew?`<label class="field destination-name"><span>新档案名称</span><input id="import-new-name" value="${escapeHtml(d.newName)}" maxlength="40" aria-describedby="new-import-error"><small class="field-error" id="new-import-error"></small></label>`:''}</fieldset><table class="diff-table"><thead><tr><th>数据</th><th>此次导入</th><th>应用规则</th></tr></thead><tbody>${r.rows.map(row=>`<tr><td>${row[0]}</td><td><b class="${row[1].includes('替换')?'replace':''}">${row[1]}</b></td><td>${row[2]}</td></tr>`).join('')}</tbody></table>${d.source==='account'?cardStrip('mini-roster'):''}<p class="dialog-note">应用后：${number(r.cards)} 张游戏卡牌${r.customCount?` · ${r.customCount} 张自定义卡牌`:``} · ${r.items} 件道具 · ${r.characters} 位角色。</p>${d.server!==p.server||d.format==='bestdori'&&d.source==='paste'?`<div class="notice info server-changed">${icon('info')}<div><b>${isNew?'新档案':'目标档案'}使用 ${servers[d.server]}</b><p>${isNew?'原档案保持不变。':'服务器筛选将同步更新；已有持有记录按上表规则处理。'}</p></div></div>`:''}<p class="dialog-note">${isNew?'新建并切换到导入的档案；原档案保持不变。':`${d.source==='account'?'只新增和修改，未返回的卡牌、道具和角色加成保留。':''}只更新上表列出的内容，活动与计算参数保留。`}</p></div><div class="dialog-bottom"><button class="text-button" id="import-back">${icon('arrow')}返回修改</button><button class="primary" id="apply-import">${isNew?'创建并导入':'应用到此档案'}</button></div>`;
}
export function importDoneMarkup({d,p,r,name="",copy=null,isNew=false,compact=true,payload="",escapeHtml,serverChoices,flagInline,flag,icon,importScope,cardStrip=()=>"",servers,number=String}) {
const stepList = step => `<ol class="step-list" aria-label="导入进度"><li class="${step===1?'active':''}"><i>1</i>读取资料</li><li class="${step===2?'active':''}"><i>2</i>核对变化</li><li class="${step===3?'active':''}"><i>3</i>完成</li></ol>`;
return `<div class="flow-body">${stepList(3)}<div class="parse-state"><div class="check-disc">${icon('check')}</div><h3>「${escapeHtml(p.name)}」已更新</h3><p>${number(p.cards)} 张游戏卡牌${p.customCount?` · ${p.customCount} 张自定义卡牌`:``} · ${p.items} 件道具 · ${p.characters} 位角色<br>可以继续检查卡牌，或回到活动配置。</p></div></div><div class="dialog-bottom"><button class="text-button" data-close-flow>留在档案管理</button><div class="actions"><a class="text-button" href="#cards">查看卡牌</a><a class="primary" href="#activity">配置活动 ${icon('arrow')}</a></div></div>`;
}
export function exportMarkup({d,p,r,name="",copy=null,isNew=false,compact=true,payload="",escapeHtml,serverChoices,flagInline,flag,icon,importScope,cardStrip=()=>"",servers,number=String}) {
const stepList = step => `<ol class="step-list" aria-label="导入进度"><li class="${step===1?'active':''}"><i>1</i>读取资料</li><li class="${step===2?'active':''}"><i>2</i>核对变化</li><li class="${step===3?'active':''}"><i>3</i>完成</li></ol>`;
return `<div class="flow-body"><div class="export-heading">${flag(p.server)}<b>${escapeHtml(p.name)}</b><span>${number(p.cards)} 张游戏卡牌${p.customCount?` · ${p.customCount} 张自定义卡牌`:``} · ${p.items} 件道具</span></div><div class="export-options"><label class="export-option"><input type="radio" name="export-format" value="base64" ${compact?'checked':''}><span><b>本工具 · Base64</b><span class="recommend">适合迁移养成配置</span><small>游戏卡牌、自定义卡牌（含图片与启用状态）、区域道具、角色潜能与任务加成。</small></span></label><label class="export-option"><input type="radio" name="export-format" value="bestdori" ${!compact?'checked':''}><span><b>Bestdori Profile</b><small>用于与 Bestdori 交换卡牌、道具和潜能配置。</small></span></label></div>${compact?`<div class="coverage-line"><span>${icon('check')}卡牌状态</span><span>${icon('check')}道具等级</span><span>${icon('check')}完整角色加成</span></div><p class="format-warning">此格式不含档案名称、玩家 ID、服务器、活动配置和历史结果。导入时使用目标档案的这些设置。</p>`:`<p class="format-warning">此格式不支持自定义卡牌；需要保留时请选择本工具 Base64。角色任务加成和分项自定义潜能也无法完整保留。不包含玩家 ID、活动配置及历史结果。</p>`}<label class="field"><span>导出内容 <small></small></span><textarea class="export-preview" id="export-text" readonly rows="6" spellcheck="false">${escapeHtml(payload)}</textarea></label><div id="export-status" role="status"></div></div><div class="dialog-bottom"><button class="text-button" data-close-flow>关闭</button><div class="actions"><button class="text-button" id="download-export">${icon('download')}下载文本</button><button class="primary" id="copy-export">${icon('copy')}复制配置</button></div></div>`;
}
