[package]
name = "bangdream-optimize-core"
version = "0.3.6"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bangdream-optimize-medley-solver.workspace = true
bangdream-optimize-team-prune.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen.workspace = true

[build-dependencies]
serde_json.workspace = true

[dev-dependencies]
